### ISSUE TITLE
UEFI shell, Python 3.6.8 type error

### ISSUE THREAD

**Issue by fpmurphy** [chipsec/chipsec#1377]
It appears that the update to Python 3 has broken something.  I am getting "TypeError: argument 3 must be str, not bytes" when I invoke "chipsec_util.py spi dump rom.bin" from a UEFI shell.

Here is the full error:

################################################################
################################################################
[CHIPSEC] Version : 1.8.0
[CHIPSEC] OS      : uefi   
[CHIPSEC] Python  : 3.6.8 (64-bit)

[CHIPSEC] API mode: using CHIPSEC kernel module API
[CHIPSEC] Helper  : EfiHelper (None)
[CHIPSEC] Platform: Mobile 8th Generation Core Processor (Kabylake U-Quad Core)
[CHIPSEC]      VID: 8086
[CHIPSEC]      DID: 5914
[CHIPSEC]      RID: 08
[CHIPSEC] PCH     : PCH-U with iHDCP 2.2 Premium
[CHIPSEC]      VID: 8086
[CHIPSEC]      DID: 9D4E
[CHIPSEC]      RID: 21
[CHIPSEC] Executing command 'spi' with args ['dump', 'rom.bin']

[CHIPSEC] Dumping entire SPI flash memory to 'rom.bin'
[CHIPSEC] it may take a few minutes (use DEBUG or VERBOSE logger options to see progress)
[CHIPSEC] BIOS region: base = 0x00700000, limit = 0x00FFFFFF
[CHIPSEC] Dumping 0x01000000 bytes (to the end of BIOS region)
[spi] reading 0x1000000 bytes from SPI at FLA = 0x0 (in 262144 0x40-byte chunks + 0x0-byte remainder)
Traceback (most recent call last):
  File "chipsec_util.py", line 218, in <module>
    sys.exit( main() )
  File "chipsec_util.py", line 214, in main
    return chipsecUtil.main()
  File "chipsec_util.py", line 189, in main
    comm.run()
  File "FS1:\chipsec\chipsec\utilcmd\spi_cmd.py", line 182, in run
    self.func()
  File "FS1:\chipsec\chipsec\utilcmd\spi_cmd.py", line 108, in spi_dump
    buf = self._spi.read_spi_to_file( 0, spi_size, self.out_file )
  File "FS1:\chipsec\chipsec\hal\spi.py", line 564, in read_spi_to_file
    buf = self.read_spi( spi_fla, data_byte_count )
  File "FS1:\chipsec\chipsec\hal\spi.py", line 592, in read_spi
    cycle_done = self._wait_SPI_flash_cycle_done()
  File "FS1:\chipsec\chipsec\hal\spi.py", line 507, in _wait_SPI_flash_cycle_done
    self.spi_reg_write( self.hsfs_off, HSFSTS_CLEAR, 1 )
  File "FS1:\chipsec\chipsec\hal\spi.py", line 243, in spi_reg_write
    return self.mmio.write_MMIO_reg(self.rcba_spi_base, reg, value, size)
  File "FS1:\chipsec\chipsec\hal\mmio.py", line 112, in write_MMIO_reg
    self.cs.helper.write_mmio_reg( bar_base, size, value, offset, bar_size )
  File "FS1:\chipsec\chipsec\helper\oshelper.py", line 192, in write_mmio_reg
    ret = self.helper.write_mmio_reg(bar_base +offset, size, value )
  File "FS1:\chipsec\chipsec\helper\efi\efihelper.py", line 166, in write_mmio_reg
    edk2.writemem(phys_address_lo, phys_address_hi, buf, size)
TypeError: argument 3 must be str, not bytes

**Comment by fpmurphy** [comment]
@frinzell Yes, your fix worked

**Comment by frinzell** [comment]
Thanks!
