### ISSUE TITLE
Windows Error when running chipsec_main with --skip_config and -n option

### ISSUE THREAD

**Issue by BrentHoltsclaw** [chipsec/chipsec#1765]
Within chipsec_main line 406 chipsec is calling get_cpuid without a driver loaded.  

```
[CHIPSEC] Version  : 1.10.4
[CHIPSEC] Arguments: -i -n --skip_config -m tools.uefi.scan_image -a generate H08_1.84_10_23_2020.signed.flash.bin

WARNING: Platform dependent functionality is likely to be incorrect

Traceback (most recent call last):
  File "..\chipsec-brent\chipsec_main.py", line 490, in <module>
    sys.exit(main())
  File "..\chipsec-brent\chipsec_main.py", line 485, in main
    return chipsecMain.main()
  File "..\chipsec-brent\chipsec_main.py", line 471, in main
    modules_failed = self.run_loaded_modules()
  File "..\chipsec-brent\chipsec_main.py", line 293, in run_loaded_modules
    results.add_properties(self.properties())
  File "..\chipsec-brent\chipsec_main.py", line 406, in properties
    ret["Platform"] = "{}, CPUID: {}, VID: {:04X}, DID: {:04X}, RID: {:02X}".format(self._cs.longname, self._cs.get_cpuid(), self._cs.vid,
  File "C:\tmp\tmp\chipsec-brent\chipsec\chipset.py", line 186, in get_cpuid
    (eax, ebx, ecx, edx) = self.cpu.cpuid(0x01, 0x00)
  File "C:\tmp\tmp\chipsec-brent\chipsec\hal\cpu.py", line 60, in cpuid
    (eax, ebx, ecx, edx) = self.helper.cpuid(eax, ecx)
  File "C:\tmp\tmp\chipsec-brent\chipsec\helper\oshelper.py", line 431, in cpuid
    ret = self.helper.cpuid(eax, ecx)
  File "C:\tmp\tmp\chipsec-brent\chipsec\helper\win\win32helper.py", line 901, in cpuid
    out_buf = self._ioctl(IOCTL_CPUID, in_buf, out_length)
  File "C:\tmp\tmp\chipsec-brent\chipsec\helper\win\win32helper.py", line 537, in _ioctl
    _handle_error("chipsec kernel driver is not loaded (in native API mode?)")
  File "C:\tmp\tmp\chipsec-brent\chipsec\helper\win\win32helper.py", line 241, in _handle_error
    raise OsHelperError(err, hr)
chipsec.exceptions.OsHelperError: chipsec kernel driver is not loaded (in native API mode?)
```

**Comment by npmitche** [comment]
Bin file can be found here: https://github.com/chipsec/chipsec/files/11260770/LZMAF86_rar.zip
