### ISSUE TITLE
1.13.2 missing module_ids.json when installing

### ISSUE THREAD

**Issue by npmitche** [chipsec/chipsec#2201]
Chipsec  1.13.2

See an error that the file module_ids.json is not found.

Traceback (most recent call last):
  File "/usr/bin/chipsec_main", line 33, in <module>
    sys.exit(load_entry_point('chipsec==1.13.2', 'console_scripts', 'chipsec_main')())
  File "/usr/lib/python3.7/site-packages/chipsec_main.py", line 455, in main
    return chipsecMain.main()
  File "/usr/lib/python3.7/site-packages/chipsec_main.py", line 435, in main
    self.load_module(self._module, self.moduleargv)
  File "/usr/lib/python3.7/site-packages/chipsec_main.py", line 204, in load_module
    module = chipsec.module.Module(module_name)
  File "/usr/lib/python3.7/site-packages/chipsec/module.py", line 45, in __init
    self.module_ids = self.get_module_ids_dictionary()
  File "/usr/lib/python3.7/site-packages/chipsec/module.py", line 82, in get_module_ids_dictionary
    with open(os.path.join(os.getcwd(), 'chipsec', 'library', 'module_ids.json'), 'r') as module_ids_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/chipsec/library/module_ids.json'

**Comment by npmitche** [comment]
Confirmed it's fixed with #2184
