### ISSUE TITLE
chipsec_util uefi decode fails

### ISSUE THREAD

**Issue by skochinsky** [chipsec/chipsec#68]
```
[CHIPSEC] Parsing EFI volumes from '/home/igor/rom_new1.bin'..
Traceback (most recent call last):
  File "chipsec_util.py", line 214, in <module>
    ec = chipsecUtil.main(argv)
  File "chipsec_util.py", line 181, in main
    comm.run()
  File "/home/igor/chipsec/source/tool/chipsec/utilcmd/uefi_cmd.py", line 237, in run
    decode_uefi_region(_uefi, cur_dir, filename, fwtype)
  File "/home/igor/chipsec/source/tool/chipsec/hal/spi_uefi.py", line 496, in decode_uefi_region
    parse_uefi_region_from_file( _uefi, fname, fwtype, fv_pth )
  File "/home/igor/chipsec/source/tool/chipsec/hal/spi_uefi.py", line 483, in parse_uefi_region_from_file
    traverse_uefi_region( _uefi, rom, fwtype, outpath, True, True )
  File "/home/igor/chipsec/source/tool/chipsec/hal/spi_uefi.py", line 458, in traverse_uefi_region
    if dumpall: _uefi.parse_EFI_variables( os.path.join(file_dir_path, 'DEFAULT_NVRAM'), FvImage, False, FWType.EFI_FW_TYPE_NVAR )
NameError: global name 'file_dir_path' is not defined

```

IIRC it did work a couple months ago.

**Comment by c7zero** [comment]
This issue should be closed by #73
